export const projects = [
  {
    id: 1,
    title: "929 Exam",
    type: "Web Application",
    description: "This is a Web development course ...",
    role: "In this project, I developed the website based on requirements to be able to pass this examination",
    date: 2019,
    techstack: ["React", "Bootstrap", "Javascript", "HTML", "CSS"],
    responsibilities: ["Development"],
    img: "/projects-imgs/test.png",
    alt: "929 Exam",
    src: "https://github.com/ppinng/929-Final-Exam",
  },
  {
    id: 2,
    title: "ModLifes",
    type: "Web Application",
    description:
      "ModLifes is a project of integrated project that  in 1st year, This website is a platform for KMUTT student. It has many features such as talk with another student in KMUTT, to do list, nearby restaurants, and many more.",
    role: "In this project, we separated into many group based on their features. I was in the group that responsible for the to do restaurant feature. We designed the wireframe of the feature and developed the feature.",
    date: 2022,
    techstack: [
      "React",
      "TypeScript",
      "Node.js",
      "ChakraUI",
      "Prisma",
      "Axios",
      "PostgreSQL",
      "Figma",
    ],
    responsibilities: ["Design", "Development", "Testing"],
    img: "/projects-imgs/test.png",
    alt: "ModLifes",
    src: "https://github.com/CSSIT22/studentlife",
  },
  {
    id: 3,
    title: "Arai Gor Dai",
    type: "Mobile Application",
    description:
      "Arai Gor Dai is a project of User-Centered Mobile Application Development and Agile Software Engineering course. It is a mobile application that helps people to find all food menu in KMUTT. This application has many features such as random food, show all food, and filter the food that user desire to eat It is developed by using Flutter and Firebase.",
    role: "In this project, I designed the UI/UX of the application and developed the application.",
    date: 2023,
    techstack: ["Flutter", "Firebase", "Figma"],
    responsibilities: ["Design", "Development", "Testing"],
    img: "/projects-imgs/test.png",
    alt: "Arai Gor Dai",
    src: "https://github.com/ppinng/araigordaiwithme",
  },
  {
    id: 4,
    title: "Warn Alert",
    type: "Mobile Application",
    description:
      "Warn Alert is a project of integrated project. It is an application to discover or report the dangerous areas near your that reported by fellow users, empowering you with life-saving knowledge to avoid risks or take immediate action before it too late.",
    role: "In this project, I designed database, created API endpoints, and connect Backend to Frontend.",
    date: 2023,
    techstack: ["Flutter", "NodeJS", "ExpressJS", "Figma", "PostgreSQL"],
    responsibilities: ["Development", "Testing"],
    img: "/projects-imgs/test.png",
    src: "https://github.com/ppinng/warnalertwithme",
  },
  {
    id: 5,
    title: "My Portfolio",
    type: "Web Application",
    description:
      "This is my portfolio website that I created to show my projects and skills.",
    role: "In this project, I designed the UI/UX of the website and developed the website.",
    date: 2023,
    techstack: ["React", "Vite", "Tailwind CSS", "Figma", "Boxicons"],
    responsibilities: ["Design", "Development"],
    img: "/projects-imgs/test.png",
    alt: "My Portfolio",
    src: "https://github.com/ppinng/my-portfolio",
  },
];
